[package]
name = "portage-repo"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "MIT"
description = "Gentoo ebuild repository layout reader based on PMS"
repository = "https://github.com/lu-zero/portage-repo"
keywords = ["gentoo", "portage", "repository", "pms"]
categories = ["parser-implementations", "development-tools"]

[dependencies]
portage-atom = "0.3.1"
portage-metadata = "0.2.1"
brush-core = { path = "../brush/brush-core", features = ["experimental-parser"] }
brush-builtins = { path = "../brush/brush-builtins" }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["rt"] }
regex = "1"
thiserror = "2"
jwalk = "0.8.1"
flume = "0.12.0"

[dev-dependencies]
libc = "0.2"
tempfile = "3"
tokio = { version = "1", features = ["rt", "macros"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
